/************ 16. Funciones de FECHA y HORA en SQL Server **************/
-- UTC (Universal Type)

-- HIGHER PRESISION
SELECT SYSDATETIME()		as 'SYSDATETIME';
SELECT SYSDATETIMEOFFSET()	as 'SYSDATETIMEOFFSET';
SELECT SYSUTCDATETIME()		as 'SYSUTCDATETIME';

-- LOWER PRESISION
SELECT GETDATE()			as 'GETDATE';
SELECT CURRENT_TIMESTAMP	as 'CURRENT_TIMESTAMP';
SELECT GETUTCDATE()			as 'GETUTCDATE';

-- GET PART OF DATE
SELECT DATEPART(YEAR, GETDATE()); -- YEAR - año
SELECT DATEPART(MONTH, '2020-01-15'); -- MONTH - mes
SELECT DATEPART(WEEK, '2020-01-15'); -- WEEK - semana
SELECT DATEPART(DAY, '2020-01-15'); -- DAY - dia
SELECT DATENAME(MONTH, '2020-01-15'); -- DAY - dia

-- cambiar idioma
SET LANGUAGE 'Spanish';

-- GE DIFFERENCES VALUES VALUES FROM
SELECT DATEDIFF(DAY, '2021-06-10', '2021-06-16') as 'DiasTranscurridos'; --dias
SELECT DATEDIFF(MONTH, '2021-06-10', '2021-06-16') as 'MesesTranscurridos'; --meses
SELECT DATEDIFF(YEAR, '2015-06-10', '2021-06-16') as 'AñosTranscurridos'; --años



SELECT DATEDIFF_BIG(NANOSECOND, GETDATE() - 1, GETDATE()); 

-- MODIFY DATA
SELECT GETDATE() + 5;	-- forma1
SELECT DATEADD(DAY, 5, GETDATE());-- forma2

SELECT DATEADD(YEAR, 5, GETDATE());







